// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Howl LLC
// AUTO-GENERATED by scripts/optimize-landing-images.mjs. Do not edit by hand.
// Intrinsic size of each screenshot's PNG fallback and the responsive widths
// available as <name>-<w>.avif / <name>-<w>.webp under /public/landing/screenshots/.
export interface ShotMeta {
  w: number;
  h: number;
  widths: number[];
}

export const LANDING_SHOTS: Record<string, ShotMeta> = {
  "appearance-1": { w: 1920, h: 1135, widths: [640, 1280, 1920] },
  "appearance-2": { w: 1920, h: 1178, widths: [640, 1280, 1920] },
  "appearance-3": { w: 1920, h: 928, widths: [640, 1280, 1920] },
  "applications": { w: 1920, h: 1383, widths: [640, 1280, 1920] },
  "auto-filter": { w: 1920, h: 1411, widths: [640, 1280, 1920] },
  "calendar": { w: 1918, h: 922, widths: [640, 1280, 1918] },
  "chat-final": { w: 1919, h: 925, widths: [640, 1280, 1919] },
  "entry-rules": { w: 1920, h: 1384, widths: [640, 1280, 1920] },
  "privacy-encryption": { w: 1430, h: 1493, widths: [640, 1280, 1430] },
  "privacy-social": { w: 1385, h: 1563, widths: [640, 1280, 1385] },
  "roles": { w: 1920, h: 1385, widths: [640, 1280, 1920] },
  "safety": { w: 1920, h: 1562, widths: [640, 1280, 1920] },
  "self-roles": { w: 1920, h: 1450, widths: [640, 1280, 1920] },
  "server-calendar": { w: 1917, h: 927, widths: [640, 1280, 1917] },
  "showcase-real": { w: 1494, h: 1696, widths: [640, 1280, 1494] },
};
