// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Howl LLC
export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: string[];
}

export interface EmojiSearchEntry {
  emoji: string;
  keywords: string;
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'people',
    label: 'People',
    icon: '😀',
    emojis: [
      '😀','😃','😄','😁','😆','😅','🤣','😂','🙂','🙃',
      '😉','😊','😇','🥰','😍','🤩','😘','😗','☺️','😚',
      '😙','🥲','😋','😛','😜','🤪','😝','🤑','🤗','🤭',
      '🤫','🤔','🫡','🤐','🤨','😐','😑','😶','🫥','😏',
      '😒','🙄','😬','🤥','😌','😔','😪','🤤','😴','😷',
      '🤒','🤕','🤢','🤮','🥵','🥶','🥴','😵','🤯','🤠',
      '🥳','🥸','😎','🤓','🧐','😕','🫤','😟','🙁','☹️',
      '😮','😯','😲','😳','🥺','🥹','😦','😧','😨','😰',
      '😥','😢','😭','😱','😖','😣','😞','😓','😩','😫',
      '🥱','😤','😡','😠','🤬','😈','👿','💀','☠️','💩',
      '🤡','👹','👺','👻','👽','👾','🤖','😺','😸','😹',
      '😻','😼','😽','🙀','😿','😾','🙈','🙉','🙊',
      '👋','🤚','🖐️','✋','🖖','🫱','🫲','🫳','🫴','👌',
      '🤌','🤏','✌️','🤞','🫰','🤟','🤘','🤙','👈','👉',
      '👆','🖕','👇','☝️','🫵','👍','👎','✊','👊','🤛',
      '🤜','👏','🙌','🫶','👐','🤲','🤝','🙏','✍️','💅',
      '🤳','💪','🦾','🦿','🦵','🦶','👂','🦻','👃','🧠',
      '🫀','🫁','🦷','🦴','👀','👁️','👅','👄','🫦',
      '👶','🧒','👦','👧','🧑','👱','👨','🧔','👩','🧓',
      '👴','👵','🙍','🙎','🙅','🙆','💁','🙋','🧏','🙇',
      '🤦','🤷','💆','💇','🚶','🧍','🧎','🏃','💃','🕺',
      '👯','🧖','🧗','🤸','⛹️','🏋️','🚴','🚵','🤼','🤽',
      '🤾','🤺','🏇','⛷️','🏂','🏌️','🏄','🚣','🏊','🤹',
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    icon: '🐻',
    emojis: [
      '🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐻‍❄️','🐨',
      '🐯','🦁','🐮','🐷','🐽','🐸','🐵','🙈','🙉','🙊',
      '🐒','🐔','🐧','🐦','🐤','🐣','🐥','🦆','🦅','🦉',
      '🦇','🐺','🐗','🐴','🦄','🐝','🪱','🐛','🦋','🐌',
      '🐞','🐜','🪰','🪲','🪳','🦟','🦗','🕷️','🕸️','🦂',
      '🐢','🐍','🦎','🦖','🦕','🐙','🦑','🦐','🦞','🦀',
      '🐡','🐠','🐟','🐬','🐳','🐋','🦈','🦭','🐊','🐅',
      '🐆','🦓','🦍','🦧','🐘','🦛','🦏','🐪','🐫','🦒',
      '🦘','🦬','🐃','🐂','🐄','🐎','🐖','🐏','🐑','🦙',
      '🐐','🦌','🐕','🐩','🦮','🐕‍🦺','🐈','🐈‍⬛','🪶','🐓',
      '🦃','🦤','🦚','🦜','🦢','🦩','🕊️','🐇','🦝','🦨',
      '🦡','🦫','🦦','🦥','🐁','🐀','🐿️','🦔',
      '🌵','🎄','🌲','🌳','🌴','🪵','🌱','🌿','☘️','🍀',
      '🎍','🪴','🎋','🍃','🍂','🍁','🪺','🪹','🍄','🌾',
      '💐','🌷','🌹','🥀','🌺','🌸','🌼','🌻','🌞','🌝',
      '🌛','🌜','🌚','🌕','🌖','🌗','🌘','🌑','🌒','🌓',
      '🌔','🌙','🌎','🌍','🌏','🪐','💫','⭐','🌟','✨',
      '⚡','☄️','💥','🔥','🌪️','🌈','☀️','🌤️','⛅','🌥️',
      '☁️','🌦️','🌧️','⛈️','🌩️','🌨️','❄️','☃️','⛄','🌬️',
      '💨','💧','💦','🫧','☔','☂️','🌊','🌫️',
    ],
  },
  {
    id: 'food',
    label: 'Food & Drink',
    icon: '🍔',
    emojis: [
      '🍇','🍈','🍉','🍊','🍋','🍌','🍍','🥭','🍎','🍏',
      '🍐','🍑','🍒','🍓','🫐','🥝','🍅','🫒','🥥','🥑',
      '🍆','🥔','🥕','🌽','🌶️','🫑','🥒','🥬','🥦','🧄',
      '🧅','🍄','🥜','🫘','🌰','🍞','🥐','🥖','🫓','🥨',
      '🥯','🥞','🧇','🧀','🍖','🍗','🥩','🥓','🍔','🍟',
      '🍕','🌭','🥪','🌮','🌯','🫔','🥙','🧆','🥚','🍳',
      '🥘','🍲','🫕','🥣','🥗','🍿','🧈','🧂','🥫','🍱',
      '🍘','🍙','🍚','🍛','🍜','🍝','🍠','🍢','🍣','🍤',
      '🍥','🥮','🍡','🥟','🥠','🥡','🦀','🦞','🦐','🦑',
      '🦪','🍦','🍧','🍨','🍩','🍪','🎂','🍰','🧁','🥧',
      '🍫','🍬','🍭','🍮','🍯','🍼','🥛','☕','🫖','🍵',
      '🍶','🍾','🍷','🍸','🍹','🍺','🍻','🥂','🥃','🫗',
      '🥤','🧋','🧃','🧉','🧊','🥢','🍽️','🥄','🔪','🫙',
      '🏺',
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    icon: '⚽',
    emojis: [
      '⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🥏','🎱',
      '🪀','🏓','🏸','🏒','🏑','🥍','🏏','🪃','🥅','⛳',
      '🪁','🏹','🎣','🤿','🥊','🥋','🎽','🛹','🛼','🛷',
      '⛸️','🥌','🎿','⛷️','🏂','🪂','🏋️','🤼','🤸','⛹️',
      '🤺','🤾','🏌️','🏇','🧘','🏄','🏊','🤽','🚣','🧗',
      '🚴','🚵','🎖️','🏆','🥇','🥈','🥉','🏅','🎗️','🎪',
      '🤹','🎭','🩰','🎨','🎬','🎤','🎧','🎼','🎹','🥁',
      '🪘','🎷','🎺','🪗','🎸','🪕','🎻','🪈','🎲','♟️',
      '🎯','🎳','🎮','🕹️','🎰','🧩',
    ],
  },
  {
    id: 'travel',
    label: 'Travel & Places',
    icon: '✈️',
    emojis: [
      '🚗','🚕','🚙','🚌','🚎','🏎️','🚓','🚑','🚒','🚐',
      '🛻','🚚','🚛','🚜','🦯','🦽','🦼','🛴','🚲','🛵',
      '🏍️','🛺','🚨','🚔','🚍','🚘','🚖','🛞','🚡','🚠',
      '🚟','🚃','🚋','🚞','🚝','🚄','🚅','🚈','🚂','🚆',
      '🚇','🚊','🚉','✈️','🛫','🛬','🛩️','💺','🛰️','🚀',
      '🛸','🚁','🛶','⛵','🚤','🛥️','🛳️','⛴️','🚢','⚓',
      '🪝','⛽','🚧','🚦','🚥','🛑','🚏',
      '🗺️','🗿','🗽','🗼','🏰','🏯','🏟️','🎡','🎢','🎠',
      '⛲','⛱️','🏖️','🏝️','🏜️','🌋','⛰️','🏔️','🗻','🏕️',
      '⛺','🛖','🏠','🏡','🏘️','🏚️','🏗️','🏭','🏢','🏬',
      '🏣','🏤','🏥','🏦','🏨','🏪','🏫','🏩','💒','🏛️',
      '⛪','🕌','🛕','🕍','⛩️','🕋','⛰️','🌅','🌄','🌠',
      '🎇','🎆','🌇','🌆','🏙️','🌃','🌌','🌉','🌁',
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      '⌚','📱','📲','💻','⌨️','🖥️','🖨️','🖱️','🖲️','🕹️',
      '🗜️','💽','💾','💿','📀','📼','📷','📸','📹','🎥',
      '📽️','🎞️','📞','☎️','📟','📠','📺','📻','🎙️','🎚️',
      '🎛️','🧭','⏱️','⏲️','⏰','🕰️','⌛','⏳','📡','🔋',
      '🪫','🔌','💡','🔦','🕯️','🪔','🧯','🛢️','💸','💵',
      '💴','💶','💷','🪙','💰','💳','💎','⚖️','🪜','🧰',
      '🪛','🔧','🔨','⚒️','🛠️','⛏️','🪚','🔩','⚙️','🪤',
      '🧱','⛓️','🧲','🔫','💣','🧨','🪓','🔪','🗡️','⚔️',
      '🛡️','🚬','⚰️','🪦','⚱️','🏺','🔮','📿','🧿','🪬',
      '💈','⚗️','🔭','🔬','🕳️','🩹','🩺','🩻','🩼','💊',
      '💉','🩸','🧬','🦠','🧫','🧪','🌡️','🧹','🪠','🧺',
      '🧻','🚽','🚰','🚿','🛁','🛀','🧼','🪥','🪒','🧽',
      '🪣','🧴','🛎️','🔑','🗝️','🚪','🪑','🛋️','🛏️','🛌',
      '🧸','🪆','🖼️','🪞','🪟','🛍️','🛒','🎁','🎈','🎏',
      '🎀','🪄','🪅','🎊','🎉','🎎','🏮','🎐','🧧','✉️',
      '📩','📨','📧','💌','📥','📤','📦','🏷️','🪧',
      '📪','📫','📬','📭','📮','📯','📜','📃','📄','📑',
      '🧾','📊','📈','📉','🗒️','🗓️','📆','📅','🗑️','📇',
      '🗃️','🗳️','🗄️','📋','📁','📂','🗂️','🗞️','📰','📓',
      '📔','📒','📕','📗','📘','📙','📚','📖','🔖','🧷',
      '🔗','📎','🖇️','📐','📏','🧮','📌','📍','✂️','🖊️',
      '🖋️','✒️','🖌️','🖍️','📝','✏️','🔍','🔎','🔏','🔐',
      '🔒','🔓',
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '❤️',
    emojis: [
      '❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','💔',
      '❤️‍🔥','❤️‍🩹','❣️','💕','💞','💓','💗','💖','💘','💝',
      '💟','☮️','✝️','☪️','🕉️','☸️','✡️','🔯','🕎','☯️',
      '☦️','🛐','⛎','♈','♉','♊','♋','♌','♍','♎',
      '♏','♐','♑','♒','♓','🆔','⚛️','🉑','☢️','☣️',
      '📴','📳','🈶','🈚','🈸','🈺','🈷️','✴️','🆚','💮',
      '🉐','㊙️','㊗️','🈴','🈵','🈹','🈲','🅰️','🅱️','🆎',
      '🆑','🅾️','🆘','❌','⭕','🛑','⛔','📛','🚫','💯',
      '💢','♨️','🚷','🚯','🚳','🚱','🔞','📵','🚭','❗',
      '❕','❓','❔','‼️','⁉️','🔅','🔆','〽️','⚠️','🚸',
      '🔱','⚜️','🔰','♻️','✅','🈯','💹','❇️','✳️','❎',
      '🌐','💠','Ⓜ️','🌀','💤','🏧','🚾','♿','🅿️','🛗',
      '🈳','🈂️','🛂','🛃','🛄','🛅','🚹','🚺','🚻','🚼',
      '🚮','🎦','📶','🈁','🔣','ℹ️','🔤','🔡','🔠','🆖',
      '🆗','🆙','🆒','🆕','🆓','0️⃣','1️⃣','2️⃣','3️⃣','4️⃣',
      '5️⃣','6️⃣','7️⃣','8️⃣','9️⃣','🔟','🔢','#️⃣','*️⃣',
      '⏏️','▶️','⏸️','⏯️','⏹️','⏺️','⏭️','⏮️','⏩','⏪',
      '⏫','⏬','◀️','🔼','🔽','➡️','⬅️','⬆️','⬇️','↗️',
      '↘️','↙️','↖️','↕️','↔️','↪️','↩️','⤴️','⤵️','🔀',
      '🔁','🔂','🔄','🔃','🎵','🎶','➕','➖','➗','✖️',
      '🟰','♾️','💲','💱','™️','©️','®️','👁️‍🗨️','🔚','🔙',
      '🔛','🔝','🔜','〰️','➰','➿','✔️','☑️','🔘','🔴',
      '🟠','🟡','🟢','🔵','🟣','⚫','⚪','🟤','🔺','🔻',
      '🔸','🔹','🔶','🔷','🔳','🔲','▪️','▫️','◾','◽',
      '◼️','◻️','🟥','🟧','🟨','🟩','🟦','🟪','⬛','⬜',
      '🟫','🔈','🔇','🔉','🔊','🔔','🔕','📣','📢',
      '🏁','🚩','🎌','🏴','🏳️','🏳️‍🌈','🏳️‍⚧️','🏴‍☠️',
    ],
  },
  {
    id: 'flags',
    label: 'Flags',
    icon: '🏁',
    emojis: [
      '🇺🇸','🇬🇧','🇨🇦','🇦🇺','🇩🇪','🇫🇷','🇪🇸','🇮🇹','🇯🇵','🇰🇷',
      '🇨🇳','🇮🇳','🇧🇷','🇲🇽','🇷🇺','🇿🇦','🇳🇬','🇪🇬','🇸🇦','🇦🇪',
      '🇹🇷','🇳🇱','🇸🇪','🇳🇴','🇩🇰','🇫🇮','🇵🇱','🇺🇦','🇬🇷','🇵🇹',
      '🇦🇷','🇨🇴','🇨🇱','🇵🇪','🇻🇪','🇨🇺','🇵🇭','🇮🇩','🇹🇭','🇻🇳',
      '🇲🇾','🇸🇬','🇳🇿','🇮🇪','🇨🇭','🇦🇹','🇧🇪','🇭🇺','🇨🇿','🇷🇴',
      '🇮🇱','🇵🇰','🇧🇩','🇱🇰','🇳🇵','🇰🇪','🇬🇭','🇹🇼','🇭🇰','🇲🇴',
    ],
  },
];

export const EMOJI_SEARCH_INDEX: EmojiSearchEntry[] = [
  { emoji: '😀', keywords: 'grinning face happy smile' },
  { emoji: '😃', keywords: 'grinning face big eyes smile happy' },
  { emoji: '😄', keywords: 'grinning face smiling eyes happy' },
  { emoji: '😁', keywords: 'beaming face grin teeth' },
  { emoji: '😆', keywords: 'grinning squinting face laugh lol xd' },
  { emoji: '😅', keywords: 'grinning face sweat nervous awkward' },
  { emoji: '🤣', keywords: 'rolling floor laughing rofl lol' },
  { emoji: '😂', keywords: 'face tears joy crying laughing lol' },
  { emoji: '🙂', keywords: 'slightly smiling face' },
  { emoji: '🙃', keywords: 'upside down face' },
  { emoji: '😉', keywords: 'winking face wink' },
  { emoji: '😊', keywords: 'smiling face smiling eyes blush' },
  { emoji: '😇', keywords: 'smiling face halo angel innocent' },
  { emoji: '🥰', keywords: 'smiling face hearts love' },
  { emoji: '😍', keywords: 'heart eyes smiling love' },
  { emoji: '🤩', keywords: 'star struck eyes excited amazed' },
  { emoji: '😘', keywords: 'face blowing kiss love' },
  { emoji: '😗', keywords: 'kissing face' },
  { emoji: '☺️', keywords: 'smiling face relaxed' },
  { emoji: '😚', keywords: 'kissing closed eyes' },
  { emoji: '😙', keywords: 'kissing smiling eyes' },
  { emoji: '🥲', keywords: 'smiling face tear sad happy' },
  { emoji: '😋', keywords: 'face savoring food yummy delicious' },
  { emoji: '😛', keywords: 'face tongue out' },
  { emoji: '😜', keywords: 'winking face tongue silly' },
  { emoji: '🤪', keywords: 'zany face crazy wild goofy' },
  { emoji: '😝', keywords: 'squinting face tongue' },
  { emoji: '🤑', keywords: 'money mouth face dollar rich' },
  { emoji: '🤗', keywords: 'hugging face hug' },
  { emoji: '🤭', keywords: 'face hand over mouth oops giggle' },
  { emoji: '🤫', keywords: 'shushing face quiet secret' },
  { emoji: '🤔', keywords: 'thinking face hmm wonder' },
  { emoji: '🫡', keywords: 'saluting face salute respect' },
  { emoji: '🤐', keywords: 'zipper mouth face shut quiet' },
  { emoji: '🤨', keywords: 'raised eyebrow suspicious' },
  { emoji: '😐', keywords: 'neutral face blank' },
  { emoji: '😑', keywords: 'expressionless face blank' },
  { emoji: '😶', keywords: 'face without mouth silent' },
  { emoji: '🫥', keywords: 'dotted line face invisible hidden' },
  { emoji: '😏', keywords: 'smirking face smirk flirty' },
  { emoji: '😒', keywords: 'unamused face annoyed meh' },
  { emoji: '🙄', keywords: 'rolling eyes face whatever' },
  { emoji: '😬', keywords: 'grimacing face awkward cringe' },
  { emoji: '🤥', keywords: 'lying face pinocchio liar' },
  { emoji: '😌', keywords: 'relieved face calm' },
  { emoji: '😔', keywords: 'pensive face sad thoughtful' },
  { emoji: '😪', keywords: 'sleepy face tired' },
  { emoji: '🤤', keywords: 'drooling face drool' },
  { emoji: '😴', keywords: 'sleeping face zzz sleep' },
  { emoji: '😷', keywords: 'face medical mask sick' },
  { emoji: '🤒', keywords: 'face thermometer sick ill fever' },
  { emoji: '🤕', keywords: 'face head bandage hurt injured' },
  { emoji: '🤢', keywords: 'nauseated face sick green' },
  { emoji: '🤮', keywords: 'face vomiting throw up sick' },
  { emoji: '🥵', keywords: 'hot face sweating heat' },
  { emoji: '🥶', keywords: 'cold face freezing frozen' },
  { emoji: '🥴', keywords: 'woozy face dizzy drunk' },
  { emoji: '😵', keywords: 'face crossed out eyes dizzy' },
  { emoji: '🤯', keywords: 'exploding head mind blown shocked' },
  { emoji: '🤠', keywords: 'cowboy hat face western' },
  { emoji: '🥳', keywords: 'partying face party celebration birthday' },
  { emoji: '🥸', keywords: 'disguised face nose glasses incognito' },
  { emoji: '😎', keywords: 'smiling face sunglasses cool' },
  { emoji: '🤓', keywords: 'nerd face glasses smart' },
  { emoji: '🧐', keywords: 'face monocle inspect curious' },
  { emoji: '😕', keywords: 'confused face' },
  { emoji: '🫤', keywords: 'face diagonal mouth unsure' },
  { emoji: '😟', keywords: 'worried face concern' },
  { emoji: '🙁', keywords: 'slightly frowning face sad' },
  { emoji: '☹️', keywords: 'frowning face sad' },
  { emoji: '😮', keywords: 'face open mouth surprised' },
  { emoji: '😯', keywords: 'hushed face surprised quiet' },
  { emoji: '😲', keywords: 'astonished face shocked wow' },
  { emoji: '😳', keywords: 'flushed face embarrassed blushing' },
  { emoji: '🥺', keywords: 'pleading face puppy eyes begging' },
  { emoji: '🥹', keywords: 'face holding back tears emotional' },
  { emoji: '😦', keywords: 'frowning face open mouth' },
  { emoji: '😧', keywords: 'anguished face worried' },
  { emoji: '😨', keywords: 'fearful face scared afraid' },
  { emoji: '😰', keywords: 'anxious face sweat nervous' },
  { emoji: '😥', keywords: 'sad but relieved face' },
  { emoji: '😢', keywords: 'crying face tear sad' },
  { emoji: '😭', keywords: 'loudly crying face bawling sob' },
  { emoji: '😱', keywords: 'face screaming fear scared' },
  { emoji: '😖', keywords: 'confounded face' },
  { emoji: '😣', keywords: 'persevering face struggling' },
  { emoji: '😞', keywords: 'disappointed face sad' },
  { emoji: '😓', keywords: 'downcast face sweat' },
  { emoji: '😩', keywords: 'weary face tired exhausted' },
  { emoji: '😫', keywords: 'tired face exhausted' },
  { emoji: '🥱', keywords: 'yawning face bored tired' },
  { emoji: '😤', keywords: 'face steam nose triumph angry' },
  { emoji: '😡', keywords: 'pouting face angry red mad' },
  { emoji: '😠', keywords: 'angry face mad' },
  { emoji: '🤬', keywords: 'face symbols mouth swearing cursing' },
  { emoji: '😈', keywords: 'smiling face horns devil evil' },
  { emoji: '👿', keywords: 'angry face horns imp devil' },
  { emoji: '💀', keywords: 'skull dead death skeleton' },
  { emoji: '☠️', keywords: 'skull crossbones death pirate' },
  { emoji: '💩', keywords: 'pile poo poop' },
  { emoji: '🤡', keywords: 'clown face' },
  { emoji: '👹', keywords: 'ogre monster japanese' },
  { emoji: '👺', keywords: 'goblin monster japanese' },
  { emoji: '👻', keywords: 'ghost halloween boo spooky' },
  { emoji: '👽', keywords: 'alien extraterrestrial ufo' },
  { emoji: '👾', keywords: 'alien monster space invader' },
  { emoji: '🤖', keywords: 'robot face' },
  { emoji: '😺', keywords: 'grinning cat happy' },
  { emoji: '😸', keywords: 'grinning cat smiling eyes' },
  { emoji: '😹', keywords: 'cat tears joy laughing' },
  { emoji: '😻', keywords: 'smiling cat heart eyes love' },
  { emoji: '😼', keywords: 'cat wry smile smirk' },
  { emoji: '😽', keywords: 'kissing cat' },
  { emoji: '🙀', keywords: 'weary cat scared' },
  { emoji: '😿', keywords: 'crying cat sad' },
  { emoji: '😾', keywords: 'pouting cat angry' },
  { emoji: '🙈', keywords: 'see no evil monkey' },
  { emoji: '🙉', keywords: 'hear no evil monkey' },
  { emoji: '🙊', keywords: 'speak no evil monkey' },
  { emoji: '👋', keywords: 'waving hand hello hi bye' },
  { emoji: '🤚', keywords: 'raised back hand' },
  { emoji: '🖐️', keywords: 'hand splayed fingers open' },
  { emoji: '✋', keywords: 'raised hand stop high five' },
  { emoji: '🖖', keywords: 'vulcan salute spock' },
  { emoji: '👌', keywords: 'ok hand perfect fine' },
  { emoji: '🤌', keywords: 'pinched fingers italian' },
  { emoji: '🤏', keywords: 'pinching hand small tiny' },
  { emoji: '✌️', keywords: 'victory hand peace sign two' },
  { emoji: '🤞', keywords: 'crossed fingers luck hope' },
  { emoji: '🫰', keywords: 'hand index thumb crossed money snap' },
  { emoji: '🤟', keywords: 'love you gesture ily' },
  { emoji: '🤘', keywords: 'sign horns rock metal' },
  { emoji: '🤙', keywords: 'call me hand shaka' },
  { emoji: '👈', keywords: 'pointing left hand' },
  { emoji: '👉', keywords: 'pointing right hand' },
  { emoji: '👆', keywords: 'pointing up hand' },
  { emoji: '🖕', keywords: 'middle finger' },
  { emoji: '👇', keywords: 'pointing down hand' },
  { emoji: '☝️', keywords: 'index pointing up one' },
  { emoji: '🫵', keywords: 'index pointing at viewer you' },
  { emoji: '👍', keywords: 'thumbs up good yes like approve' },
  { emoji: '👎', keywords: 'thumbs down bad no dislike' },
  { emoji: '✊', keywords: 'raised fist power solidarity' },
  { emoji: '👊', keywords: 'oncoming fist bump punch' },
  { emoji: '🤛', keywords: 'left facing fist bump' },
  { emoji: '🤜', keywords: 'right facing fist bump' },
  { emoji: '👏', keywords: 'clapping hands applause bravo' },
  { emoji: '🙌', keywords: 'raising hands celebration hooray' },
  { emoji: '🫶', keywords: 'heart hands love' },
  { emoji: '👐', keywords: 'open hands' },
  { emoji: '🤲', keywords: 'palms up together prayer' },
  { emoji: '🤝', keywords: 'handshake agreement deal' },
  { emoji: '🙏', keywords: 'folded hands pray please thank you' },
  { emoji: '✍️', keywords: 'writing hand' },
  { emoji: '💅', keywords: 'nail polish manicure beauty' },
  { emoji: '🤳', keywords: 'selfie phone camera' },
  { emoji: '💪', keywords: 'flexed biceps muscle strong' },
  { emoji: '👀', keywords: 'eyes look see watch' },
  { emoji: '👁️', keywords: 'eye look see watch' },
  { emoji: '👅', keywords: 'tongue lick taste' },
  { emoji: '👄', keywords: 'mouth lips kiss' },
  { emoji: '🔥', keywords: 'fire flame hot lit' },
  { emoji: '💯', keywords: 'hundred points perfect score' },
  { emoji: '💥', keywords: 'collision boom explosion' },
  { emoji: '💫', keywords: 'dizzy star sparkle' },
  { emoji: '✨', keywords: 'sparkles shine glitter magic' },
  { emoji: '⭐', keywords: 'star yellow' },
  { emoji: '🌟', keywords: 'glowing star shine bright' },
  { emoji: '⚡', keywords: 'high voltage lightning bolt electric zap' },
  { emoji: '❄️', keywords: 'snowflake cold winter frozen' },
  { emoji: '☀️', keywords: 'sun sunny bright hot' },
  { emoji: '🌈', keywords: 'rainbow colors' },
  { emoji: '☁️', keywords: 'cloud weather' },
  { emoji: '🌊', keywords: 'water wave ocean sea surf' },
  { emoji: '🌸', keywords: 'cherry blossom flower spring pink' },
  { emoji: '🌹', keywords: 'rose flower red love' },
  { emoji: '🌻', keywords: 'sunflower flower' },
  { emoji: '🍀', keywords: 'four leaf clover lucky luck' },
  { emoji: '🐶', keywords: 'dog face puppy' },
  { emoji: '🐱', keywords: 'cat face kitten' },
  { emoji: '🐻', keywords: 'bear face' },
  { emoji: '🐼', keywords: 'panda face' },
  { emoji: '🦊', keywords: 'fox face' },
  { emoji: '🦁', keywords: 'lion face king' },
  { emoji: '🐸', keywords: 'frog face' },
  { emoji: '🐵', keywords: 'monkey face' },
  { emoji: '🦄', keywords: 'unicorn face magical' },
  { emoji: '🐝', keywords: 'honeybee bee honey' },
  { emoji: '🦋', keywords: 'butterfly' },
  { emoji: '🐢', keywords: 'turtle tortoise slow' },
  { emoji: '🐍', keywords: 'snake' },
  { emoji: '🐙', keywords: 'octopus' },
  { emoji: '🦈', keywords: 'shark fish' },
  { emoji: '🐬', keywords: 'dolphin flipper' },
  { emoji: '🐳', keywords: 'whale spouting ocean' },
  { emoji: '🐘', keywords: 'elephant' },
  { emoji: '🦒', keywords: 'giraffe' },
  { emoji: '🍔', keywords: 'hamburger burger food' },
  { emoji: '🍕', keywords: 'pizza slice food' },
  { emoji: '🌮', keywords: 'taco mexican food' },
  { emoji: '🍟', keywords: 'french fries chips food' },
  { emoji: '🍦', keywords: 'ice cream soft serve dessert' },
  { emoji: '🍩', keywords: 'doughnut donut sweet' },
  { emoji: '🍪', keywords: 'cookie sweet biscuit' },
  { emoji: '🎂', keywords: 'birthday cake celebration' },
  { emoji: '🍰', keywords: 'shortcake cake slice dessert' },
  { emoji: '🍫', keywords: 'chocolate bar candy' },
  { emoji: '☕', keywords: 'hot beverage coffee tea' },
  { emoji: '🍺', keywords: 'beer mug drink' },
  { emoji: '🍻', keywords: 'clinking beer mugs cheers drink' },
  { emoji: '🍷', keywords: 'wine glass drink' },
  { emoji: '🍹', keywords: 'tropical drink cocktail' },
  { emoji: '🥤', keywords: 'cup straw soda drink' },
  { emoji: '⚽', keywords: 'soccer ball football' },
  { emoji: '🏀', keywords: 'basketball' },
  { emoji: '🏈', keywords: 'american football' },
  { emoji: '⚾', keywords: 'baseball ball' },
  { emoji: '🎾', keywords: 'tennis ball racket' },
  { emoji: '🏆', keywords: 'trophy winner champion prize' },
  { emoji: '🥇', keywords: 'first place gold medal winner' },
  { emoji: '🎮', keywords: 'video game controller gaming' },
  { emoji: '🎲', keywords: 'game die dice' },
  { emoji: '🎯', keywords: 'direct hit bullseye target' },
  { emoji: '🎨', keywords: 'artist palette painting art' },
  { emoji: '🎬', keywords: 'clapper board movie film' },
  { emoji: '🎤', keywords: 'microphone karaoke sing' },
  { emoji: '🎧', keywords: 'headphone music audio' },
  { emoji: '🎹', keywords: 'musical keyboard piano' },
  { emoji: '🎸', keywords: 'guitar music rock' },
  { emoji: '🎉', keywords: 'party popper celebration tada' },
  { emoji: '🎊', keywords: 'confetti ball celebration party' },
  { emoji: '🎈', keywords: 'balloon party celebration' },
  { emoji: '🎁', keywords: 'wrapped gift present birthday' },
  { emoji: '🚗', keywords: 'automobile car vehicle' },
  { emoji: '✈️', keywords: 'airplane plane flight travel' },
  { emoji: '🚀', keywords: 'rocket space launch' },
  { emoji: '🛸', keywords: 'flying saucer ufo alien' },
  { emoji: '🏠', keywords: 'house building home' },
  { emoji: '🏖️', keywords: 'beach umbrella vacation' },
  { emoji: '⛰️', keywords: 'mountain' },
  { emoji: '🌅', keywords: 'sunrise' },
  { emoji: '🌌', keywords: 'milky way galaxy night sky stars' },
  { emoji: '💻', keywords: 'laptop computer' },
  { emoji: '📱', keywords: 'mobile phone smartphone' },
  { emoji: '💡', keywords: 'light bulb idea' },
  { emoji: '🔑', keywords: 'key lock' },
  { emoji: '🔒', keywords: 'locked lock secure' },
  { emoji: '🔓', keywords: 'unlocked lock open' },
  { emoji: '📷', keywords: 'camera photo picture' },
  { emoji: '📹', keywords: 'video camera recording' },
  { emoji: '💰', keywords: 'money bag dollar rich' },
  { emoji: '💎', keywords: 'gem stone diamond jewel' },
  { emoji: '🔔', keywords: 'bell notification alert' },
  { emoji: '🔕', keywords: 'bell slash mute no notification' },
  { emoji: '📢', keywords: 'loudspeaker announcement' },
  { emoji: '📌', keywords: 'pushpin pin' },
  { emoji: '📎', keywords: 'paperclip clip' },
  { emoji: '✂️', keywords: 'scissors cut' },
  { emoji: '📝', keywords: 'memo writing note' },
  { emoji: '📚', keywords: 'books reading library' },
  { emoji: '🔍', keywords: 'magnifying glass search find' },
  { emoji: '❤️', keywords: 'red heart love' },
  { emoji: '🧡', keywords: 'orange heart love' },
  { emoji: '💛', keywords: 'yellow heart love' },
  { emoji: '💚', keywords: 'green heart love' },
  { emoji: '💙', keywords: 'blue heart love' },
  { emoji: '💜', keywords: 'purple heart love' },
  { emoji: '🖤', keywords: 'black heart love dark' },
  { emoji: '🤍', keywords: 'white heart love' },
  { emoji: '🤎', keywords: 'brown heart love' },
  { emoji: '💔', keywords: 'broken heart love sad' },
  { emoji: '❤️‍🔥', keywords: 'heart fire love passion' },
  { emoji: '💕', keywords: 'two hearts love' },
  { emoji: '💞', keywords: 'revolving hearts love' },
  { emoji: '💓', keywords: 'beating heart love' },
  { emoji: '💗', keywords: 'growing heart love' },
  { emoji: '💖', keywords: 'sparkling heart love' },
  { emoji: '💘', keywords: 'heart arrow cupid love' },
  { emoji: '❌', keywords: 'cross mark no wrong delete' },
  { emoji: '⭕', keywords: 'hollow red circle' },
  { emoji: '✅', keywords: 'check mark white green yes done' },
  { emoji: '❎', keywords: 'cross mark button no' },
  { emoji: '❗', keywords: 'exclamation mark red bang' },
  { emoji: '❓', keywords: 'question mark red' },
  { emoji: '‼️', keywords: 'double exclamation mark' },
  { emoji: '⁉️', keywords: 'exclamation question mark' },
  { emoji: '💤', keywords: 'zzz sleeping sleep' },
  { emoji: '➡️', keywords: 'right arrow' },
  { emoji: '⬅️', keywords: 'left arrow' },
  { emoji: '⬆️', keywords: 'up arrow' },
  { emoji: '⬇️', keywords: 'down arrow' },
  { emoji: '🔄', keywords: 'counterclockwise arrows refresh reload' },
  { emoji: '🔀', keywords: 'shuffle tracks' },
  { emoji: '🎵', keywords: 'musical note music' },
  { emoji: '🎶', keywords: 'musical notes music' },
  { emoji: '♻️', keywords: 'recycling symbol recycle green' },
  { emoji: '⚠️', keywords: 'warning sign caution alert' },
  { emoji: '🚫', keywords: 'prohibited no ban forbidden' },
  { emoji: '🏁', keywords: 'chequered flag finish race' },
  { emoji: '🚩', keywords: 'triangular flag red flag warning' },
  { emoji: '🇺🇸', keywords: 'flag united states america usa us' },
  { emoji: '🇬🇧', keywords: 'flag united kingdom uk britain gb' },
  { emoji: '🇨🇦', keywords: 'flag canada' },
  { emoji: '🇦🇺', keywords: 'flag australia' },
  { emoji: '🇩🇪', keywords: 'flag germany' },
  { emoji: '🇫🇷', keywords: 'flag france' },
  { emoji: '🇪🇸', keywords: 'flag spain' },
  { emoji: '🇮🇹', keywords: 'flag italy' },
  { emoji: '🇯🇵', keywords: 'flag japan' },
  { emoji: '🇰🇷', keywords: 'flag south korea' },
  { emoji: '🇨🇳', keywords: 'flag china' },
  { emoji: '🇮🇳', keywords: 'flag india' },
  { emoji: '🇧🇷', keywords: 'flag brazil' },
  { emoji: '🇲🇽', keywords: 'flag mexico' },
  { emoji: '🇷🇺', keywords: 'flag russia' },
];
