#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Howl LLC
// Sync the Stream Deck plugin's version to Howl's root package.json so the
// pair-handshake version, the streamdeck-plugin/package.json, the Elgato
// manifest's 4-part Version, and the runtime constant in
// src/generated/version.ts all stay aligned.
//
// Behavior:
//   - Reads ../package.json#version (Howl's root) as the source of truth.
//   - Writes that 3-part version to streamdeck-plugin/package.json#version.
//   - Writes `${version}.${build}` to manifest.json#Version (4-part).
//     `build` is normally 0; set HOWL_PLUGIN_BUILD=N to override (used for
//     Marketplace-only rebuilds that don't bump the app, e.g., icon swap).
//   - Writes src/generated/version.ts exporting HOWL_APP_VERSION as the
//     3-part string.
//
// Idempotent: re-running without changes produces identical files.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pluginRoot = join(__dirname, '..');
const repoRoot = join(pluginRoot, '..');

const SEMVER_RE = /^\d+\.\d+\.\d+$/;
const buildSegment = (() => {
  const raw = process.env.HOWL_PLUGIN_BUILD;
  if (raw === undefined || raw === '') return 0;
  const n = Number(raw);
  if (!Number.isInteger(n) || n < 0) {
    console.error(`sync-version: HOWL_PLUGIN_BUILD must be a non-negative integer, got "${raw}"`);
    process.exit(1);
  }
  return n;
})();

// Read source version
const rootPkgPath = join(repoRoot, 'package.json');
const rootPkg = JSON.parse(readFileSync(rootPkgPath, 'utf8'));
const version = rootPkg.version;
if (typeof version !== 'string' || !SEMVER_RE.test(version)) {
  console.error(`sync-version: ${rootPkgPath} version is not 3-part semver: "${version}"`);
  process.exit(1);
}

// Update streamdeck-plugin/package.json
const pluginPkgPath = join(pluginRoot, 'package.json');
const pluginPkg = JSON.parse(readFileSync(pluginPkgPath, 'utf8'));
if (pluginPkg.version !== version) {
  pluginPkg.version = version;
  writeFileSync(pluginPkgPath, JSON.stringify(pluginPkg, null, 2) + '\n', 'utf8');
  console.log(`sync-version: streamdeck-plugin/package.json version → ${version}`);
}

// Update manifest.json (4-part)
const manifestPath = join(pluginRoot, 'com.howlpro.streamdeck.sdPlugin', 'manifest.json');
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const fourPart = `${version}.${buildSegment}`;
if (manifest.Version !== fourPart) {
  manifest.Version = fourPart;
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  console.log(`sync-version: manifest.json Version → ${fourPart}`);
}

// Generate src/generated/version.ts
const generatedDir = join(pluginRoot, 'src', 'generated');
mkdirSync(generatedDir, { recursive: true });
const generatedPath = join(generatedDir, 'version.ts');
const generated = `// AUTO-GENERATED by streamdeck-plugin/scripts/sync-version.mjs.
// Do not edit by hand. Runs on every \`npm run build\` and reads
// the root package.json version. To change the version bump the root.

export const HOWL_APP_VERSION = ${JSON.stringify(version)};
`;
let needWrite = true;
try {
  if (readFileSync(generatedPath, 'utf8') === generated) needWrite = false;
} catch { /* file doesn't exist yet */ }
if (needWrite) {
  writeFileSync(generatedPath, generated, 'utf8');
  console.log(`sync-version: src/generated/version.ts → HOWL_APP_VERSION = "${version}"`);
}

