// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Howl LLC
/**
 * Pin the sframe.v1 encoding so that any change to the X25519 box
 * primitive or key-distribution wire format is caught immediately.
 *
 * Uses fixed seeds and nonce so the output is fully deterministic.
 */
import { describe, it, expect } from 'vitest';
import nacl from 'tweetnacl';

const toB64 = (u: Uint8Array) => btoa(String.fromCharCode(...u));

describe('sframe.v1 encoding stability', () => {
  it('known X25519 inputs produce known ciphertext', () => {
    // Fixed inputs for determinism.
    const leaderSeed = new Uint8Array(32).fill(7);
    const joinerSeed = new Uint8Array(32).fill(8);
    const leaderKP = nacl.box.keyPair.fromSecretKey(leaderSeed);
    const joinerKP = nacl.box.keyPair.fromSecretKey(joinerSeed);
    const sessionKey = new Uint8Array(32).fill(0x42);
    const nonce = new Uint8Array(24).fill(0x33);

    const boxed = nacl.box(sessionKey, nonce, joinerKP.publicKey, leaderKP.secretKey);
    const actualBase64 = toB64(boxed);

    // Pinned value generated by first run — any change to the X25519 box
    // output will fail this test loudly.
    const expectedBase64 = 'LvCowFYNjCumIr33/lRNce8A05l96vSqgMpXqyo+Qvhx7dKmNKhAG+u2hmuN+d4h';
    expect(actualBase64).toBe(expectedBase64);
  });
});
